version: '3.1' 
services: 
  sonar-server: 
    image: sonarqube:8.9.1-community 
    ports: 
      - 8125:9000 
   
  sonar-scanner: 
    image: maven:3.6.3-openjdk-8  
    build: 
      context: . 
      dockerfile: dockerfile 
    depends_on: 
      - sonar-server
